# -*- coding: utf-8 -*-
"""a2-05.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pyZKRkrqBW2Is7xK_cteVAWXQxMKz5UG
"""

import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/MyDrive/412/a2/student-mat.csv', delimiter=';')
display(df)

#Question 1
num_attributes = len(df.columns)
num_records = len(df)
#display the number of attributes and number of records
print(num_attributes, num_records)

#Question 2
# Mean of G3
mean_G3 = df['G3'].mean()
# Median of G3
median_G3 = df['G3'].median()
print(mean_G3, median_G3)

#Question 3 a
#Select the rows where the age is 16
df_16 = df[df['age'] == 16]
#Get the number of 16-year-old students
num_16 = len(df_16)
#Get the mean of the final grades of the 16-year-old students
mean_grade_16 = df_16['G3'].mean()
print(num_16, mean_grade_16)

#Question 3 b
#Select the rows where the age is between 16 and 18 (inclusive) and study time is more than 5
df_selected = df[(df['age'] >= 16) & (df['age'] <= 18) & (df['studytime'] >= 3)]
#Get the number of students that meet the criteria
num_selected = len(df_selected)
#Get the mean of the final grades of the selected students
mean_grade_selected = df_selected['G3'].mean()
print(num_selected, mean_grade_selected)

#Question 4
# Create the pivot table
table = df.pivot_table(values='G3', index='studytime', columns='traveltime', aggfunc='mean')

# Print the pivot table
print(table)